version: '{build}'

image: Visual Studio 2017

environment:
  QT_VER: 5.10.1

  matrix:
    # Runtime env
    #- PLATFORM: winrt_x64_msvc2017
    #- PLATFORM: winrt_x86_msvc2017
    #- PLATFORM: winrt_armv7_msvc2017
    # Dev env
    - PLATFORM: msvc2017_64
    #- PLATFORM: msvc2015_64
    #- PLATFORM: msvc2015
    #- PLATFORM: mingw53_32
    # only when using static tools
    #- PLATFORM: static
    
branches:
  only:
    - master
        
build_script:
  - C:\projects\qregovar\deploy\win\build-msvc.bat

after_build:
  - C:\projects\qregovar\deploy\win\upload-prepare.bat

artifacts:
  - path: build_*.zip

deploy:
  - provider: GitHub
    tag: v0.12.$(appveyor_build_version)
    release: Regovar v0.12.$(appveyor_build_version)
    description: ''
    auth_token:
      secure: wgjLvB8J0dtgJebFhMFyAjbnXkToKF2bfWYPl1EXkshsfBEfS/JYj7P+YFxbHNcO
    artifact:  build_*.zip
    draft: true
    prerelease: true
    on:
      branch: master                # release from master branch only
      # appveyor_repo_tag: true       # deploy on tag push only


