image: Visual Studio 2017

branches:
  only:
    - master
    
install:
  - set QTDIR=C:\Qt\5.10.1\msvc2017_64
  - set PATH=%QTDIR%\bin;C:\Qt\Tools\mingw530_32\bin;%PATH%;
  
build_script:
  - cd app
  # - qmake app/QRegovar.pro -spec win32-msvc
  - nmake qmake_all
  - nmake
  - nmake lrelease # -f Makefile.Release

deploy:
  - provider: GitHub
    artifact: C:/projects/qregovar
    draft: true
    prerelease: true
    on:
      branch: master                # release from master branch only
      # appveyor_repo_tag: true       # deploy on tag push only


