version: '{build}'

image: Visual Studio 2017

environment:
  QT_VER: 5.11.0

  matrix:
    # WinRT disabled as Regovar use QProcess and is not a fullscreen only app (see http://doc.qt.io/qt-5/winrt-support.html)
    #- PLATFORM: winrt_x64_msvc2017
    #- PLATFORM: winrt_x86_msvc2017
    #- PLATFORM: winrt_armv7_msvc2017
    # Dev env
    - PLATFORM: msvc2017_64  # 64bits
    - PLATFORM: msvc2015     # 32 its
    # Mingw compilator disabled for windows as it doesn support Chromium compilation which is required for QML WebView)
    #- PLATFORM: mingw53_32
    # only when using static tools
    #- PLATFORM: static
    
branches:
  only:
    - master
        
build_script:
  - C:\projects\qregovar\deploy\win\build-msvc.bat

after_build:
  - C:\projects\qregovar\deploy\win\upload-prepare.bat

artifacts:
  - path: build_*.zip

deploy:
  - provider: GitHub
    tag: v0.12.284
    release: Regovar v0.12.284+build.$(appveyor_build_version)
    description: ''
    auth_token:
      secure: wgjLvB8J0dtgJebFhMFyAjbnXkToKF2bfWYPl1EXkshsfBEfS/JYj7P+YFxbHNcO
    artifact:  /.*\.zip/
    draft: true
    prerelease: true
    on:
      branch: master                # release from master branch only
      # appveyor_repo_tag: true       # deploy on tag push only


