image: Visual Studio 2017

environment:
  QT_VER: 5.10.1

  matrix:
    # Runtime env
    - PLATFORM: winrt_x64_msvc2017
    #- PLATFORM: winrt_x86_msvc2017
    #- PLATFORM: winrt_armv7_msvc2017
    # Dev env
    - PLATFORM: msvc2017_64
    #- PLATFORM: msvc2015_64
    #- PLATFORM: msvc2015
    - PLATFORM: mingw53_32
    # only when using static tools
    - PLATFORM: static
    
branches:
  only:
    - master
    
install:
  - C:\projects\qregovar\deploy\win\setup.bat

build_script:
  - C:\projects\qregovar\deploy\win\build.bat

after_build:
  - C:\projects\qregovar\deploy\win\upload-prepare.bat

artifacts:
  - path: install\build_*_%QT_VER%.zip

deploy:
  - provider: GitHub
    artifact:  /.*\.zip/
    draft: true
    prerelease: true
    on:
      branch: master                # release from master branch only
      # appveyor_repo_tag: true       # deploy on tag push only


